apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.8
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: nginx-vol
        - name: shell
          image: busybox
          stdin: true
          tty: true
      volumes:
        - name: nginx-vol
          emptyDir: {}
# kubectl apply -f nginx-deployment.yaml
# kubectl get pods -l app=nginx
# kubectl delete -f nginx-deployment.yaml
