/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_content.app;

import java_content.list.LinkedList;

import static java_content.utilities.StringUtils.join;
import static java_content.utilities.StringUtils.split;
import static java_content.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
